### ISSUE TITLE
ncp-rbac.yml missing

### ISSUE THREAD

**Issue by darrylcauldwell** [vmware/nsx-integration-for-openshift#21]
I was trying to work through this today and the ncp-rbac.yml appears to be called to create the ncp-svc-account and nsx-node-agent-svc-account,  this does not seem to be a part of either this repo or the NSX CNI download package.  Could you add an example one or point me to where I can get one from please.

**Comment by kais66** [comment]
Could you refer to https://github.com/vmware/nsx-integration-for-openshift/blob/local_install/openshift-ansible-nsx/yamls/nsx-ncp-rbac.yaml first? We are in the process of testing this branch, will merge it soon to master.

**Comment by darrylcauldwell** [comment]
That appears to work,  thank you for quick response.

As this file is needed if doing a manual or Ansible install would it be better placed in the package 'NSX Container Plugin 2.2.0' along with all similar definition files?

**Comment by kais66** [comment]
It actually existed in the release package and the team decided to remove it. There must be a good reason for it but unfortunately I was not involved in that decision. Apologies for the inconvenience but once the above code is merged it will be available in this repo.

**Comment by darrylcauldwell** [comment]
No issue, should be good as long as it is available somewhere,  thank you for quick respone
