### ISSUE TITLE
NCP00003  Invalid state

### ISSUE THREAD

**Issue by darrylcauldwell** [vmware/nsx-integration-for-openshift#22]
I have NCP running,  however the pod is in CrashLoopBackOff state,  when I check the logs it shows NCP00003 I see in the admin guide this means Invalid state.

Is there any method to get more information on 'Invalid state' so I can look to fix and get this running.

**Comment by kais66** [comment]
This error could've happened because NCP replicationController has more than 1 replicas. But this is probably not related to the installation?

**Comment by darrylcauldwell** [comment]
This is my first install so doubt it would be multiple replicas.  I assume it is related to installation as this is what I am following,  however until I can work out what error actually means its impossible to say cause. Are there any logs or anything I can check rule out installation and get a better idea on cause?

**Comment by darrylcauldwell** [comment]
Yeah it is oc describe which is how I got to the error message NCP00003

Will look to start again clean build

**Comment by darrylcauldwell** [comment]
Think it must have been environmental,  got passed it with clean build.
